opts = {
    "data_dir": "../dataset/Sketch",
    "dataset": "quickdraw",
    "groups": 16,
    "max_stroke_num": 100,
    "paint_size": 256,
    "grid_nums": [7, 11, 15, 19],
    "directed_graph": True,
    "pool": True,
    "dense_connect": True,
    "multi_scale": True,
    "num_class": 345,
    "batch_size": 256,
    "train_epochs": 40,
    "test_epoch": 1,
    "save_epoch": 1,
    "lr": 2 * 1e-3,
    "weight_decay": 1e-5,
}
